### ISSUE TITLE
show BS version in the listbox?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#10]
ST3 plugin  shows labels like
`Bootstrap 2/3` (if id exists for v2 and v3).
easy to add?

**Comment by Alexey-T** [comment]
https://raw.githubusercontent.com/jfcherng-sublime/ST-BootstrapAutocomplete/st4/docs/screenshot-st4.png

**Comment by halfbrained** [comment]
Added

![vers](https://user-images.githubusercontent.com/74829192/128979085-1604d236-70c9-45e4-b91c-02892dba3f59.png)
