### ISSUE TITLE
addition to readme

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#14]
Options
-------
Plugin has the option to specify Bootstrap versions to use. Value must be comma-separated numbers like "4" or "3,4".

a) To set it globally, call "Options / Settings-plugins / Bootstrap Completion / Config", and write the option to plugins.ini.
b) To set it per-project, open dialog "Project properties" (in the context menu over Project Manager), and write the option to the "Variables" input field.

**Comment by halfbrained** [comment]
Added, thanks
