### ISSUE TITLE
maybe support spaces around '='?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#17]
```
  <div class = "row">
```
not single space, but 1+ spaces.

**Comment by Alexey-T** [comment]
an idea-
instead of
`PREFIX = 'class="'`

add regex
```
PREFIX_RE = r'class\x20*=\x20*['"]'
```

**Comment by halfbrained** [comment]
Yeah, I searched about this earlier, every example was with double-quotes. But I found answered in the spec, it can be even without quotes. Fixing
https://html.spec.whatwg.org/multipage/introduction.html#a-quick-introduction-to-html:syntax-attributes
> The attribute value can remain unquoted if it doesn't contain ASCII whitespace or any of " ' ` = < or >. Otherwise, it has to be quoted using either single or double quote

**Comment by halfbrained** [comment]
I misplaced my last message, it was regarding single-quoted attributes #16.

About this issue - spec says not spaces (url above):
> consist of a name and a value, separated by an "=" character

And it doesn't make sense after '=', since attribute value can be unquoted. Thus there is probably also no need to support space before '='?

**Comment by Alexey-T** [comment]
I agree. closing..
