### ISSUE TITLE
i18n from Markus

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#18]
[__init__.zip](https://github.com/halfbrained/cuda_bootstrap_complete/files/6982412/__init__.zip)

**Comment by Alexey-T** [comment]
no need as I see now.

**Comment by Alexey-T** [comment]
Markus wrote:

>Well, it seems okay, but GNU Gettext does not handle _(_msg). I tested
that before I sent you the message.

>You can even remove the surrounding _() from _(_msg):
              res = msg_box(_msg, MB_OKCANCEL + MB_ICONINFO)
I missed that, sorry.

**Comment by halfbrained** [comment]
Applied

> GNU Gettext does not handle _(_msg)

Will keep that in mind
