### ISSUE TITLE
Plugin request for lexer JS

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_bootstrap_complete#19]
Is it possible to create/adapt a plugin for Cud from this link?

https://github.com/pichillilorenzo/JavaScript-Completions

**Comment by eltonfabricio10** [comment]
I liked cuda_bootstrap_complete :)

**Comment by Alexey-T** [comment]
it is another 'intelligent auto complete'? but why, we already have LSP-
https://wiki.freepascal.org/CudaText_plugins#LSP_server_for_JavaScript.2FReactJS

**Comment by eltonfabricio10** [comment]
Ok, I'll test it
