### ISSUE TITLE
maybe we can convert .json to .py to import it? to startup faster?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#2]
fill will begin as
```
DATA = [
```

**Comment by halfbrained** [comment]
For me reading and parsing the db takes 19ms on HDD - this happens on the first completion event. 

If you think this needs to be improved, I checked - loading it in pickled format is faster - 1.7ms to import `pickle`, 0.8ms to load the data. Should be the fastest option?

**Comment by Alexey-T** [comment]
I don’t use pickle-/ why not to convert db to a py file/ must be even faster

**Comment by halfbrained** [comment]
Changed to .py . Now it's 3ms from second app run onward
