### ISSUE TITLE
Bug with multi-carets call - wrong quotes

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#22]
I see some problem here because plugin activates on multi-carets. IMO it should not. 

And this is a bug:

after this text and carets:

![Screenshot from 2021-09-28 13-35-43](https://user-images.githubusercontent.com/4154978/135071634-a2714b87-a7f2-405b-8f53-4369490a1d69.png)

plugin CAN be activated and it gives BROKEN text (after choosing text "badge")
![Screenshot from 2021-09-28 13-35-46](https://user-images.githubusercontent.com/4154978/135071714-0c0381db-c90c-44ce-8909-2b72a5b1f72c.png)

@halfbrained

**Comment by eltonfabricio10** [comment]
OK

**Comment by Alexey-T** [comment]
Pls move this req to a new issue - to not loose it inside bugreport here.

**Comment by eltonfabricio10** [comment]
@veksha

@Alexey-T enable issue in Cudatext Addons please

**Comment by Alexey-T** [comment]
issue is not visible now. seems it was solved already. closing.

**Comment by veksha** [comment]
i see bug
![image](https://user-images.githubusercontent.com/275333/192589797-4e235377-172a-44e2-8304-12035e207f76.png)

**Comment by Alexey-T** [comment]
Pls tell how to repro.
from this
```
<a href="" class=| ></a>
<a href="" class=| ></a>
<a href="" class=| ></a>
<a href="" class=| ></a>
<a href="" class= ></a>
```
plug don't activate!
from this
```
<a href="" class=ac| ></a>
<a href="" class=ac| ></a>
<a href="" class=ac| ></a>
<a href="" class= ></a>
<a href="" class= ></a>

```
plug resets multi-carets to 1 caret.

**Comment by veksha** [comment]
you can't reproduce due to another bug:
1. autocompletion listbox is not appearing with multicarets inside "class" attribute value!
2. try to move multicarets to the left (to word "class") and press `ctrl+space`
3. listbox appears, press Esc.
4. after that move multicarets back inside "class" atrribute value. only now listbox appears on `ctrl+space`

**Comment by Alexey-T** [comment]
it's made so specially. look into plugin's on_complete(). it has logic for multi-carets. in some cases, it disables plugin work for m-carets, in some cases code sets single caret.

**Comment by Alexey-T** [comment]
opened 'issuess' here. let's move here:
https://github.com/CudaText-addons/cuda_bootstrap_complete/issues

**Comment by veksha** [comment]
https://github.com/CudaText-addons/cuda_bootstrap_complete/issues/1
