### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#3]
I call it on line 21
after `"col`
![Screenshot from 2021-08-10 15-19-15](https://user-images.githubusercontent.com/4154978/128865664-7ef4da12-c334-4f4b-864c-16b9e5705c18.png)

**Comment by halfbrained** [comment]
Huh, that's weird, investigating

**Comment by halfbrained** [comment]
Should be fixed, please check.

I probably didn't get the exception because I'm still on Python3.6 :)
