### ISSUE TITLE
caret at the end of quoted-str

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#5]
`    <div class="card-img-bottom|">`
I call ctrl+space, choose some attr, and get broken value.
now ST handles this?

**Comment by Alexey-T** [comment]
and here!
`    <div class="|card-header-tabs">`

**Comment by Alexey-T** [comment]
IMO better to insert result with space. if caret at end of str-- space before chosen item.
if caret at begin- space after chosen item.

**Comment by halfbrained** [comment]
Added
