### ISSUE TITLE
caret in class="b|"

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#6]
but I get still the all-values list. I expect to get list of `b*`

**Comment by Alexey-T** [comment]
![Screenshot from 2021-08-10 16-40-23](https://user-images.githubusercontent.com/4154978/128877397-2e9cc696-9d2e-4359-8dc5-5d63981752a7.png)

**Comment by halfbrained** [comment]
I assumed new class needs to be inserted in this situation... an oversight, fixing it

**Comment by Alexey-T** [comment]
"b" is not the full class name, so treat 'b' as partial name.
