### ISSUE TITLE
I change proj-opts and it's not changed

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_bootstrap_complete#7]
- new project, add some dir
- save as ~/tst.cuda-proj
- restart Cud
- open proj, call plugin config of proj, add `4,5`

![Screenshot from 2021-08-10 16-49-56](https://user-images.githubusercontent.com/4154978/128879003-0312a880-3a1d-476d-be44-2e7da4a64055.png)

- proj file was not changed! and Cud's dialog project-config dont show new opt

**Comment by Alexey-T** [comment]
![Screenshot from 2021-08-10 16-52-36](https://user-images.githubusercontent.com/4154978/128879290-7fa3d12e-5775-488f-aa03-0eb28a401023.png)

**Comment by Alexey-T** [comment]
Let's not make it hard, show the user steps how to config the project via ProjMan dlg. he will write all stuff.

**Comment by halfbrained** [comment]
Ok

(It doesn't work if the `vars` is empty (or wasn't "initialized"), in this case I get a random list from `dict.get`. It completely stopped working for me and I thought i was having an stroke :) )

**Comment by halfbrained** [comment]
Fixed.

In the dialog with instructions if OK is pressed I open the project properties window. And if my option is already present - I skip the dialog and open the project properties

Opening project properties seems pretty straightforward
`app_proc(PROC_EXEC_PLUGIN, 'cuda_project_man,config_proj,')`
